import React from 'react';

export default function ExportedReportsTable() {
  const reports = [
    {
      id: 1,
      name: 'Monthly Maintenance Overview',
      date: 'May 01, 2026',
      type: 'Summary',
      format: 'PDF',
      by: 'Admin User'
    },
    {
      id: 2,
      name: 'Building Asset Performance',
      date: 'Apr 28, 2026',
      type: 'Detailed Log',
      format: 'Excel',
      by: 'Admin User'
    },
    {
      id: 3,
      name: 'Q1 Issue Resolution Statistics',
      date: 'Apr 15, 2026',
      type: 'Summary',
      format: 'PDF',
      by: 'Admin User'
    }
  ];

  return (
    <div className="bg-surface rounded-xl shadow-sm border border-outline-variant/20 overflow-hidden mt-6">
      <div className="p-5 border-b border-outline-variant/20 flex justify-between items-center">
        <h3 className="font-h3 text-on-surface">Recent Exported Reports</h3>
        <button className="text-secondary font-label-md hover:underline flex items-center gap-1">
          View All History <span className="material-symbols-outlined text-[18px]">arrow_forward</span>
        </button>
      </div>
      
      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-primary-container text-on-primary-container font-label-lg border-b border-outline-variant/20">
              <th className="py-3 px-5">Report Name</th>
              <th className="py-3 px-5">Date Generated</th>
              <th className="py-3 px-5">Type</th>
              <th className="py-3 px-5">Generated By</th>
              <th className="py-3 px-5 text-right">Action</th>
            </tr>
          </thead>
          <tbody>
            {reports.map((report, index) => (
              <tr 
                key={report.id} 
                className={`${index % 2 === 0 ? 'bg-white' : 'bg-surface-container-lowest'} hover:bg-primary-fixed/20 transition-colors border-b border-outline-variant/10 last:border-0`}
              >
                <td className="py-3 px-5 flex items-center gap-3">
                  <span className={`material-symbols-outlined ${report.format === 'PDF' ? 'text-red-500' : 'text-blue-500'}`}>
                    {report.format === 'PDF' ? 'picture_as_pdf' : 'table_chart'}
                  </span>
                  <span className="font-body-md text-on-surface">{report.name}</span>
                </td>
                <td className="py-3 px-5 font-body-sm text-on-surface-variant">
                  {report.date}
                </td>
                <td className="py-3 px-5">
                  <span className="bg-surface-container-highest text-on-surface font-label-sm rounded-full px-2.5 py-1 text-[12px]">
                    {report.type}
                  </span>
                </td>
                <td className="py-3 px-5 font-body-sm text-on-surface-variant">
                  {report.by}
                </td>
                <td className="py-3 px-5 text-right">
                  <button className="w-8 h-8 rounded-full hover:bg-surface-variant flex items-center justify-center text-secondary transition-colors" title="Download">
                    <span className="material-symbols-outlined text-[20px]">download</span>
                  </button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
